version: "3"
services:
  nginx:
    image: nginx:1.18
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./index.html:/var/www/html/index.html
  ipfs:
    image: ipfs/go-ipfs:latest
    ports:
       - "4001:4001"
       - "5001:5001"
       - "8080:8080"
    volumes:
      - ./ipfs:/data/ipfs